apiVersion: v1
kind: Secret
metadata:
  name: execution-service-secret
  namespace: execution-service
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongo:CHANGE_ME@mongodb-service.execution-service.svc.cluster.local:27017/execution_service?authSource=admin"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
